server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    absolute_redirect off;
    port_in_redirect off;

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }
}
