name: Deploy to Firebase Hosting on merge (PROD)

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build React App
        run: npm run build
        env:
          REACT_APP_API_URL: https://api.zenya.com.mx
          REACT_APP_API_KEY: zenya-api-prod-2026

      - name: 📁 Nest build under /admin
        run: |
          mkdir -p admin_build/admin
          mv build/* admin_build/admin/
          rm -rf build
          mv admin_build build

      - name: 🔥 Deploy to Firebase (PROD)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZENYA_APP_476BC }}
          channelId: live
          projectId: zenya-app-476bc