name: Deploy to Firebase Hosting on merge (STAGE)

on:
  push:
    branches:
      - stage

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build React App
        run: npm run build

      - name: 🔥 Deploy to Firebase (STAGE)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGE }}
          channelId: live
          projectId: zenya-nails-spa-stage
